### PR TITLE
Feature/465 bundler

### PR DESCRIPTION
**Pull request by thepian**
Bundler API allows you to use a specific custom bundler for a view in your SS application.

### CODE REVIEW

**Comment by kulicuu** [comment]
Very nice.

**Comment by arxpoetica** [comment]
Can someone please ‘splain the @coveralls account?

**Comment by thepian** [comment]
It's an app that monitors the PR for drops in test coverage, isn't it. I've never used it so I just assume things. Perhaps Paul can give more details

**Comment by paulbjensen** [comment]
It's a Code Coverage service which monitors code coverage % on your repos. If you integrate it with your Github repo then it will check commits and post the results to the comments section in the PR.

**Comment by arxpoetica** [comment]
Word. Thx!

**Pull request merged**
