### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/socketstream/socketstream

This was requested by a real person (user RomanMinkin) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by RomanMinkin** [comment]
Hi guys it was me, who sent this PR, looks awful  tho ;)

I wan you to consider using https://waffle.io/socketstream/socketstream for project and PR request management. I'm using it at my work and It's free for open source.

**Comment by arxpoetica** [comment]
Huh. Interesting. What do you like about it?

**Comment by RomanMinkin** [comment]
@arxpoetica, It's like https://trello.com but works with existing Github issues. or lets say it's like minified sexy JIRA for Github ;)

Here is an example how Ionicframwork's team uses it https://waffle.io/driftyco/ionic

**Comment by thepian** [comment]
I like the look of it, but lets hear some actual benefits. If we take it will it become a requirement, or optional?

**Comment by thepian** [comment]
I failed to move things into the in progress column, not sure if it's bug or restriction. The interface looks really nice though.

**Comment by thepian** [comment]
Since there seem to be no objections lets try it

**Pull request merged**
