### PR TITLE
Support system library subdirectories

### PR DESCRIPTION
**Pull request by davidsketchdeck**
Hi!
I have not properly tested this out, do not accept this code- I'm submitting this to have a discussion with you:

I'd find it really useful to support things like require('when/node'), I think this more or less gets it in there - I'd love to get this in main rather than hack my local :D

### CODE REVIEW

**Comment by thepian** [comment]
Reimplemented it for 0.4

https://github.com/socketstream/socketstream/commit/669f000ae9bc22df87b1fb8f064f2c4877d8722a

**Comment by davidsketchdeck** [comment]
A) you guys rock

B) sorry i was so slow



-- 

David MackCTO & Co-Founder, SketchDeck

sketchdeck.com




See examples of our work

**Comment by thepian** [comment]
A) Glad for the thumbs up

B) You can help by trying out 0.4 and reporting any issues you have as soon as possible, it is on the next branch and will be released in beta soon

**Comment by davidsketchdeck** [comment]
Sure! I’ll try it on an experimental branch of sketchdeck


-- 

David MackCTO & Co-Founder, SketchDeck

sketchdeck.com




See examples of our work

**Comment by thepian** [comment]
It is now released as 0.4.0-beta

**Pull request closed without merging**
