### PR TITLE
Separate cli generator

### PR DESCRIPTION
**Pull request by paulbjensen**
I've separated the CLI part of SocketStream into a new module called ss-generator, which lives here: https://github.com/socketstream/ss-generator.

The idea is to help make SocketStream's codebase easier to maintain by making it more modular and better tested.

We might be able to get rid of the test/results folder, but the new_project folder is used by some other tests (the favicon.ico test in this case).

### CODE REVIEW

**Comment by thepian** [comment]
Shouldn't test resources be in the fixtures folder ?

**Comment by paulbjensen** [comment]
They should - there's some code that needs reorganising and the new_project folder is a good case. Since ss-generator has it's own copy we don't need it for that, but there are some tests which depend on it. What we can do is make another commit to revert the accidental file deletion, as well as remove the new_project folder, and change existing tests to use it in the test/fixtures folder.

**Comment by thepian** [comment]
Running the tests will remove the README file as part of the pack file management, not so good. I have added a git checkout for the project fixture assets, but that seems like the wrong solution. An improvement on that would be appreciated. Perhaps we just shouldn't have anything checked into the abc directory and have a gitignore for it and the ensure the directory is there before those tests.

**Comment by thepian** [comment]
I'd like to suggest that we stick to merging new features into `next` (or the traditionally named `develop`) and leave master for minor fixes to the current release. That way,
-  'master' releases is currently the 0.4 line.
-  'legacy' releases is currently the 0.3 line.
- 'next'(develop) releases is currently the 0.5 line

That way we can easily manage fixes, and when we release 0.5 that be comes the new master and 0.6 the next/develop

**Comment by arxpoetica** [comment]
that sounds fine

**Comment by paulbjensen** [comment]
The PR has some fix commits in that are a bit messy. I'll close the PR and make a new one following the suggested branch procedure.

**Pull request closed without merging**
