### PR TITLE
Use ss-engine.io dependency as default

### PR DESCRIPTION
**Pull request by paulbjensen**
At the moment, there are 2 copies of ss-engine.io, one that is a separate npm module, and another that comes within SocketStream by default.

This change ports the adjustments that were made to the copy inside of SocketStream over to the npm module, and allows changes for that WebSocket engine to be done in 1 place, rather than in 2.

It also helps to reduce SocketStream's core codebase down a bit.

### CODE REVIEW

**Comment by thepian** [comment]
So SockJS is a second rate citizen?

**Comment by paulbjensen** [comment]
@thepian SockJS has always been available as a plugin - the thing is the engine.io code is in the core repo, which was copy/pasted from the ss-engine.io npm module, and @kulicuu did some changes to it to make it use the latest engine.io release.

The reason for this PR was 2 things - firstly, to have 1 place where the engine.io implementation is maintained (rather than inside both socketstream and the ss-engine.io module), as well as to reduce the amount of code that exists inside of socketstream, so we can see how all the libraries connect with each other, and be in a better position to refactor the implementation to make it more modular.

At the moment I'm manually testing the implementation, and there is a JS client error in the version of ss-engine.io which I will need to debug, so we'll need to resolve that before we can merge this in.

**Comment by thepian** [comment]
I don't think it should be done like this. I take it ss-engine.io have tweaks that need to be pulled in?

**Comment by arxpoetica** [comment]
Can you explain what you mean by "retired"—I'm wary of this approach, since I use `ss-jade` (and maybe `ss-engineio`) regularly ... ?

**Comment by thepian** [comment]
Retired meaning that they are built-in to 0.5, so you can `add('jade')` just like you would `add('html')`. You can make your own Jade formatter if you like, but I don't see any need to maintain ss-jade, so they are just there for people using <0.5

engineio is built-in today, and I've added sockjs and plan to add ws. Likewise you can make your own transport and use it.

**Comment by arxpoetica** [comment]
ah gotcha. thx

**Pull request closed without merging**
