### PR TITLE
Improved live_reload, guarding against multiple rapid reloads, issue #487

### PR DESCRIPTION
**Pull request by lafras-h**
Added API so application has some control over the process.

API use
//after	ss.client.packAssets();

ss.client.set({
  onChange:
  { DelayTime:500,
    GuardTime:4000,
    Validate:function(path, event,action){
    console.log('onChangeValidate :', path);
    return true;
    },
    Publish:function(path, event,action,pubs){ 
    console.log('onChange.Publish :', action);
    //modify pubs if needed return null to not send any pubs
    return pubs;
    }
  }});

### CODE REVIEW

**Comment by paulbjensen** [comment]
Hi, Thanks for the PR. If you could make the changes as suggested by [Codacy](https://www.codacy.com/p/1998/pr/28416), then I'll take a look and merge it in. Thanks.

**Comment by thepian** [comment]
Why the capitalised names? Is that required by live-reload?

**Comment by lafras-h** [comment]
If you refer to DelayTime,GuardTime,Publish,Validate

I will fix that when I do the revision ... old habits die hard.

**Comment by paulbjensen** [comment]
Hi, 

Is the <code>delayTime</code> attribute meant to delay executing the next reload? I tried this code snippet in my app, but it didn't seem to slow down when reloads were executed:

```
ss.client.set({
	onChange: { 
		delayTime:5000,
		guardTime:8000,
		validate: function (path, event,action) {
			console.log('onChangeValidate :', path);
			return true;
		},
		publish:function (path, event,action,pubs) { 
			console.log('onChange.Publish :', action);
			//modify pubs if needed return null to not send any pubs
			return pubs;
		}
	}
});
```

**Comment by lafras-h** [comment]
Delay time is the initial, time the first change is delayed for,
guardTime is the time after the last change.

This is a new patch, make sure are you running it against a version with 
the patch in it, check the file live_reload.js refers to guardTime

also check the location : is after setting packAssets (more or less)

if (ss.env === 'production')
	ss.client.packAssets();

ss.client.set({....

**Comment by paulbjensen** [comment]
My apologies, I forgot to link the test app to the cloned version of SocketStream containing your feature branch. It works, thank you.

I'm happy to merge it in now, and will add an item to the documentation to describe how to use the feature.

Thanks for your work.

**Pull request merged**
