### PR TITLE
Connect upgrade to version 3.3.4, Engine.io upgrade to version 1.5.1

### PR DESCRIPTION
**Pull request by kulicuu**
~~This is preliminary result, as not comprehensively tested.~~
All indications I have are that both Connect and Engine are working flawlessly.  Definitely looking for more acceptance testing (you all with your apps) to try to find any lurking issues.

Preliminary testing with my app indicates a working migration to connect v3 is here.

Will continue to push developments to this pr.

### CODE REVIEW

**Comment by kulicuu** [comment]
Also contains a fix to issue #484 .

**Comment by kulicuu** [comment]
The Codacy testing thing is a bit annoying.  It's just complaining about mixture of single and double quotes.

**Comment by thepian** [comment]
I'd like to see this merged before it grows stale.

How does it fit with the release schedule, is it supposed to go in the next release. If so conflicts should be resolved, and it should be merged if it works.

**Comment by kulicuu** [comment]
It works now afaik.

Clearly needs ot be more and better acceptance testing, so working on that angle ase well.

I'm ignoring the Codacy thing for now as nothing meaningful have I seen from the reports as yet.

**Comment by paulbjensen** [comment]
I'll try and take a look into this tonight.

**Comment by kulicuu** [comment]
I'm going to rework this to bring it into line with @thepian 's work on the new static strategy.  Hopefully will have something in a few hours.

**Pull request closed without merging**
