### PR TITLE
feature(cli): Replace CLI code with ss-generator npm

### PR DESCRIPTION
**Pull request by paulbjensen**
This replaces the CLI code with a dedicated npm module ss-generator.

### CODE REVIEW

**Comment by paulbjensen** [comment]
@thepian Any idea why the client.formatters.test file is failing? https://travis-ci.org/socketstream/socketstream/jobs/61007693. I do see this happen intermittently when running the tests on my laptop (1 in every 4/5 test runs).

**Comment by thepian** [comment]
I think it is the problem we talked about before. The directory gets deleted when running pack for production I think. Tests should properly insulate this behaviour or we should tweak the logic for cleaning up previous production server starts.

**Comment by thepian** [comment]
Did you realise that you are making this against master (0.4.x) ?

**Comment by paulbjensen** [comment]
Ah, sorry, was meant to be in next

**Comment by paulbjensen** [comment]
Closed this and opened a new one for merging into "next" here #536.

I managed to replicate the error again on my machine but on test/unit/client/index.test.js#L138. It looks like the client.packAssets and client.load function calls are synchronous, but the files might still be in the process of being generated, and so the attempts to read the packed asset files fail.

The quick workaround is to put some fs.exists calls in the code and to wait until all files exist, but I think that the better approach would be to make asset packing support a callback when it has finished generating the files. I'll have a look at the code and see if this is feasible. Let me know your thoughts.

**Comment by thepian** [comment]
I agree. The tests need a done callback. And we need to pass that to pack.

However; I plan to move out the pack logic from load so it can be called as part of a build step. While the current model of "just run your server whether dev or prod" is a good default, but there will always be people that need/want more complex production setups.

I did also think that perhaps we would want to refactor the server load/start as an async waterfall. That way it is easily testable and extensible.

**Comment by arxpoetica** [comment]
@thepian there's enough you commented here, I wonder if it should go in a separate issue?

**Comment by thepian** [comment]
@arxpoetica I think it should have an issue, but I think it belongs on our trello board. I am conscious about the impression we give about a long list of open issues.

**Comment by arxpoetica** [comment]
Ha. Isn't that a *good* thing. ;)

**Pull request closed without merging**
